### ISSUE TITLE
Migrate from 2.7 to 3.6

### ISSUE THREAD

**Issue by AwesomeTurtle** [google/python-adb#37]
`import cStringsIO ` fails with Python3 
According to "What's new in Python 3" 

> The StringIO and cStringIO modules are gone. Instead, import the io module and use io.StringIO or io.BytesIO for text and data respectively.

Also there are problems with `bytes` and `str` conversions.

**Comment by fahhem** [comment]
Python 3.6 is now supported. I'm not going to "migrate" because 2.7 is still heavily used at Google, but I'm happy to support both.

Please let me know if the types I chose are wrong anywhere. It was a bit hard to decide what should be bytes or unicode/str because the protocol is very bytes-centric, especially fastboot, but certain things are unicode/str like file names and contents. However, adb doesn't mention an encoding, so I just defaulted to utf8
